### ISSUE TITLE
Turn Jenkins workload from deployment to statefulset

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops#45]
The [official Jenkins helm chart](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml) uses statefulset instead of deployment. I believe it's reasonable.

* Jenkins does not allow two instances to use the same storage. So the replicas of Jenkins deploy cannot be bigger than 1.

## Compitable

Please don't forget the upgrade process. I mean that please make sure users can upgrade from the deployment style to statefulset way successfully.

## References
* https://helm.sh/
* [Kubernetes Deployments vs StatefulSets](https://stackoverflow.com/questions/41583672/kubernetes-deployments-vs-statefulsets)

**Comment by JohnNiang** [comment]
See https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/jenkins.yml for more help @shihaoH

**Comment by shihaoH** [comment]
> See https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/jenkins.yml for more help @shihaoH

thanks

**Comment by LinuxSuRen** [comment]
hi @shihaoH , I've sent you an invite link. Please check your email. You will be a member of the [kubesphere-sigs](https://github.com/kubesphere-sigs). Then you can assign this issue to you. Of course, you need to send the command `/assign` again.

**Comment by LinuxSuRen** [comment]
I guess the prow bot has some issues. I assigned this issue to you manually.

**Comment by shihaoH** [comment]
> I guess the prow bot has some issues. I assigned this issue to you manually.

OK, thanks

**Comment by shihaoH** [comment]
Statefulset is better to use deployment configuration or independent configuration

**Comment by AbdelouahabMbarki** [comment]
@shihaoH  you can see this tutorial in kubernetes docs  https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
Statefulset configuration isn't that different for the deployment config  , in this [kubernetes/jenkins.yml ](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/jenkins.yml) they are using **volumeClaimTemplates** it allows you to create a separate   persistent volume for each pod


![image](https://user-images.githubusercontent.com/52507296/126074570-965d503b-6f37-442a-8ca3-7a3c51e48519.png)

**Comment by shihaoH** [comment]
> @shihaoH you can see this tutorial in kubernetes docs https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
> Statefulset configuration isn't that different for the deployment config , in this [kubernetes/jenkins.yml ](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/jenkins.yml) they are using **volumeClaimTemplates** it allows you to create a separate persistent volume for each pod

@AbdelouahabMbarki Yes, I know this. 
I mean some configurations of deployment and statefulset are the same, does it need to be configured separately when switching to statefulset, or share deployment configuration values

**Comment by AbdelouahabMbarki** [comment]
i like the way you implemented this  :rocket:

**Comment by shihaoH** [comment]
Thank you for your approval
