### ISSUE TITLE
Add contact links of DevOps team into the README file

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops#47]
Available communication channels:

* https://groups.google.com/g/kubesphere-sig-devops/
* [DevOps Slack channel for English speakers](https://kubesphere.slack.com/archives/C010TH02010)
* [DevOps Slack channel for Chinese speakers](https://kubesphere.slack.com/archives/C026V4FBWBW)
* [Forum for Chinese speakers](https://kubesphere.com.cn/forum/t/DevOps)
* https://github.com/kubesphere/community/tree/master/sig-devops

If English is not your first language, please feel free to add a README file in your first language.

**Comment by AbdelouahabMbarki** [comment]
i submitted a pull request  for this issue

**Comment by LinuxSuRen** [comment]
Copy that!
