### ISSUE TITLE
Create a team in postman for ks-devops

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops#48]
Such as https://www.postman.com/linuxsuren/workspace/kubesphere-devops/overview

/priority low

**Comment by AbdelouahabMbarki** [comment]
team created :
- postman ks-devops team : https://www.postman.com/ks-devops

- postman ks-devops workspace : https://www.postman.com/ks-devops/workspace/kubesphere-devops/overview

**Comment by LinuxSuRen** [comment]
That's great. Please add me as a member of it. I'll send you my email from the Slack personal channel.

**Comment by LinuxSuRen** [comment]
hi @AbdelouahabMbarki , considering the postman ks-devops team and workspace was ready. I guess we can put a link in the README file.

**Comment by AbdelouahabMbarki** [comment]
@LinuxSuRen  ok sure i will take care of that

**Comment by AbdelouahabMbarki** [comment]
i created this pr #60  for this issue

**Comment by AbdelouahabMbarki** [comment]
@LinuxSuRen  i think we can close this also

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen i think we can close this also

Yes, we can close issues or PRs with the command `/close`.

/close
