### ISSUE TITLE
Make authentication.jwtSecret configurable

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere-sigs/ks-devops#70]
Recently, I was trying to integrate ks-devops and ks-devops-plugin into ks-installer, but something unexpected happened. When I went into devops projects page, I was kicked off the line.

At last, I found that authentication.jwtSecret was hard coded as below:

- ks-devops

https://github.com/kubesphere-sigs/ks-devops/blob/8e47133c2250165faeb07d5f12ce1873680c3ec9/charts/ks-devops/templates/config.yaml#L9

- [ks-devops-plugin](https://github.com/kubesphere-sigs/ks-devops-plugin/blob/297d271f98acd7ff7546e41b9e47461f375dd3ea/charts/ks-devops-plugin/templates/config.yaml#L9)

So we should make them configurable out of helm template to adapt other third systems.

**Comment by LinuxSuRen** [comment]
If you go deep into [here](https://github.com/kubesphere-sigs/ks-devops/tree/master/cmd/tools/jwt), you will know it. This command will rewrite it.

**Comment by LinuxSuRen** [comment]
Please just point the potential issues or problems. I cannot figure it out.

**Comment by JohnNiang** [comment]
If jwtSecret was set in helm template, the secret won't be changed by jwt tool. And if we want integrate with another system, like KubeSphere, we have to keep the secret same among ks-devops, ks-devops-plugin and ks.

**Comment by LinuxSuRen** [comment]
I got your point after discussed with you in the Slack channel.
