### ISSUE TITLE
The same account with different roles entered different items, menu display error

### ISSUE THREAD

**Issue by caojiele** [kubesphere-sigs/ks-devops#90]
Bug recurrence operation: 
* A project, the role is admin, project Settings have advanced Settings menu;
![image](https://user-images.githubusercontent.com/29936718/127817761-997080db-45ac-42f9-bab7-b5c6762dd452.png)
* Then switch to project B, the role is operator, and there is no advanced setting menu in project Settings;
![image](https://user-images.githubusercontent.com/29936718/127817838-d104004b-9bcd-4aac-bb58-88c80e48c670.png)
* Finally click back to the A project, the advanced Settings are gone.
![image](https://user-images.githubusercontent.com/29936718/127817925-b05d3405-a617-4026-aca2-ae7a116abab6.png)

**Comment by JohnNiang** [comment]
Hi @caojiele , thanks for reaching out here. I cannot reproduce this issue in the latest release. please let us know your environment as detailed as possible.

**Comment by LinuxSuRen** [comment]
hi @caojiele , thanks for pointing it. But IMO this is not an issue of DevOps. I prefer you creating it under [kubesphere/kubesphere](https://github.com/kubesphere/kubesphere/issues).

**Comment by caojiele** [comment]
> hi @caojiele , thanks for pointing it. But IMO this is not an issue of DevOps. I prefer you creating it under [kubesphere/kubesphere](https://github.com/kubesphere/kubesphere/issues).

#4109

**Comment by caojiele** [comment]
> hi @caojiele , thanks for pointing it. But IMO this is not an issue of DevOps. I prefer you creating it under [kubesphere/kubesphere](https://github.com/kubesphere/kubesphere/issues).

OK, I've recreated [it](https://github.com/kubesphere/kubesphere/issues/4109).
